name: M5Stack

on: [push, pull_request]

jobs:
  build:
    name: Test compiling using Arduino build environment for M5Stack
    runs-on: ubuntu-latest
    env:
      PLATFORM: espressif:esp32

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # primary ino file must be named after directory and same name as the directory name
          path: ./3BtnTimer

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install Libraries
        run: |
          arduino-cli lib install M5Stack
          arduino-cli lib install M5Stack-SD-Updater

      # https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/debian_ubuntu.md
      - name: Checkout espressif/arduino-esp32
        uses: actions/checkout@v3
        with:
          repository: espressif/arduino-esp32
          path: ./espressif-arduino-esp32
          submodules: true
      - name: Setup espressif:esp32
        run: |
          sudo usermod -a -G dialout $USER
          sudo pip install pyserial
          mkdir -p ~/Arduino/hardware/espressif
          mv ./espressif-arduino-esp32 ~/Arduino/hardware/espressif/esp32
          cd ~/Arduino/hardware/espressif/esp32/tools
          python3 get.py
          arduino-cli core list

      - name: Build
        run: |
          arduino-cli compile -v -b espressif:esp32:m5stack-core-esp32 3BtnTimer
      - name: Check JSON file
        run: cat 3BtnTimer/json/3BtnTimer.json | python -m json.tool > /dev/null
